import React from 'react'
import {Grid,makeStyles,Typography,Paper} from '@material-ui/core'
const styles=makeStyles({
  typ:{
   color:"white",
   fontFamily: "Dekko",

  },
  typo:{
   color:"white",
   backgroundColor:"black",
   fontWeight:"bolder",
   fontFamily: "Dekko"
  },
  grid:{
    marginTop:"59px",
    paddingLeft:"125px",  
  },
  paper:{
    width:"70px",
    padding:"0px",
  },
  tu:{
    color:"white",
   backgroundColor:"black",
   fontWeight:"bolder",
   fontFamily: "Dekko"
  }
})
const Projects = () => {
    const classes=styles()
    return (
        <>
        <Grid container spacing={1} className={classes.grid}>
         <Grid  item >
        <Typography variant="h4" className={classes.typo}>My Projects:</Typography>
           <h5 className={classes.tu}>Below were projects done by me</h5>
         </Grid>
            <Grid container spacing={1}>
   <Grid container item xs={12} >
        <Grid item xs={6} md ={6}>
        
          <Paper className="paper"><h3 className={classes.typ} >1.Social Media Website Using Mern Stack</h3>
          <p>A basic social media website which is developed using mern stack and authenticated using jwt.We can create an account and post something <br/>and like, dislike,comment just as a normal social media website. Redux is used to state management. It was designed using bootstrap. It was deployed using heroku. <br/>
<b>Project:</b><a href="https://floating-tundra-67817.herokuapp.com/">Social Media Website</a> <br/>
<b>Languages used:</b>Javascript,Node.js(js environment),css.<br/>
<b>Framework:</b>React.js ,Express.js.<br/>
<b>Database:</b>MongoDb  
</p></Paper>
        </Grid>
 </Grid>
 <Grid container item xs={12} spacing={1} >
     <Grid item xs={6} md ={6}>
      <h2></h2>
     </Grid>
        <Grid item xs={6} md ={6} >
          <Paper className="paper"><h3 className={classes.typ}>2.Expense Tracker Using React.Js</h3><p>It contain two input fields for reason of expense and expense amount which gives a history of expenses and remaining balance amount.<br/> It is developed by using React Hooks and Context Api (using useReducer and useContext hooks) <br/>
          <b>Project:</b><a href="http://Aakash0211.github.io/Expense-ap">Expense Tracker</a><br/>
<b>Languages used:</b> Javascript,CSS <br/>
<b>Framework:</b>React.js </p>
</Paper>
        </Grid>
 </Grid>
 <Grid container item xs={12} spacing={1} >
        <Grid item xs={6} md ={6}>
          <Paper className="paper"><h3 className={classes.typ}>3.Food Recipe Website</h3><p>It contains a search bar which gives the recipes of the food entered using an external api which is fetched by using axios with react hooks.<br/>
External api used for food recipes is edamam api 
Keys of the items are generated by uuid <br/>
<b>Project:</b><a href="https://aakash0211.github.io/Food-Recipe-react/">Food Recipe Website</a> <br/>
<b>Languages used:</b>Javascript,CSS,Jsx <br/>
<b>Framework:</b>React.js </p>
</Paper>
        </Grid>
 </Grid>
 <Grid container item xs={12} spacing={1} >
     <Grid item xs={6} md ={6}>
      <h2></h2>
     </Grid>
        <Grid item xs={6} md ={6} >
          <Paper className="paper"><h3 className={classes.typ}>4.Chat Server</h3><p>It contain a input form having two fields room name and name<br/> which on submitting enters a room server.It was developed by using Socket.io<br/>
          <b>Project:</b><a href="https://chat-us.netlify.app/">Chat Server</a> <br/>     
<b>Languages used:</b> Javascript,CSS <br/>
<b>Framework:</b>React.js,Node.js,Express.js,Socket.io</p>
</Paper>
        </Grid>
 </Grid>
</Grid>
            </Grid>
        </>
    )
}

export default Projects
